package GUI;

import Backend.ImportExport;
import Backend.HashTable;
import Backend.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/*
 * 11/9 Michio Takemoto
 * Uses import/export now, but we have a FEW issues
 ** 1) When invalid input, we have to reset all the buttons or reset the page itself 
 that all the fields will reset as well. As of now, if we tried to submit something
 invalid, but we correct it and submit, it will still be invalid as the old data
 doesn't leave

 */
/**
 *
 * @author asharda
 */
public class CreateAccountPanel extends javax.swing.JPanel
{

    private JPanel MainPanel;
    private GUI mainGUI;

    /**
     * Creates new form CreateAccount
     */
    public CreateAccountPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ERRORPOP = new java.awt.PopupMenu();
        firstName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        createUserAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dismissView = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        confirmPassword = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        phone3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        firstName.setText("First Name");
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
        });

        password.setText("Password");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        createUserAccount.setText("Create User Account");
        createUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserAccountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        jLabel1.setText("Bank 42");

        dismissView.setText("Back");
        dismissView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dismissViewMouseClicked(evt);
            }
        });

        username.setText("Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });

        lastName.setText("Last Name");
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
        });

        confirmPassword.setText("Password");
        confirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusGained(evt);
            }
        });

        email.setText("Email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });

        phone1.setText("Area Code");
        phone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone1FocusGained(evt);
            }
        });
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        phone2.setText("XXX");

        phone3.setText("XXXX");

        jLabel3.setText("Phone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dismissView)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(email)
                            .addComponent(confirmPassword)
                            .addComponent(createUserAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phone3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstName)
                            .addComponent(lastName))
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(dismissView)
                        .addGap(429, 429, 429))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(createUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public CreateAccountPanel(JPanel MainPanel, GUI mainGUI)
    {
        this.mainGUI = mainGUI;
        this.MainPanel = MainPanel;
        initComponents();
    }

    private void createUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserAccountActionPerformed

        boolean operationSuccessful = false;

        String name1 = firstName.getText();
        String name2 = lastName.getText();
        String user = username.getText();
        char[] input1 = password.getPassword();
        String pass1 = new String(input1);
        char[] input2 = confirmPassword.getPassword();
        String input3 = email.getText();
        String pass2 = new String(input2);
       
        String phoneNumber = phone1.getText() + phone2.getText() + phone3.getText();
        
        //phone validation
        if (phone1.getText().length() < 3 || phone2.getText().length() < 3 || phone3.getText().length() < 4)
        {
            JOptionPane.showMessageDialog(null, "Invalid phone format.\nShould be 3 digits in first two boxes, and 4 in the last box.");
        }
           
        else if (name1.length() > 0)
        {
            System.out.println("firstname");
            if (name2.length() > 0)
            {
                System.out.println("lastname");
                if (user.length() > 0)
                {
                    System.out.println("username");

                    // if (((password.getText().length()) > 0) && ((password.getText()).equals(confirmPassword.())))
                    if (((pass1.length()) > 0) && (pass1.equals(pass2)))
                        System.out.println("pass1");
                    System.out.println("pass2");
                    {
                        System.out.println("test1");
                        if ((input3.length() > 0) && (isValidEmailAddress(input3)))
                        {
                            System.out.println("email");
                            System.out.println("test2");

                            if (validatePhoneNumber(phoneNumber))
                            {
                                System.out.println("phone");
                                System.out.println("test3");
                                System.out.println("test4");

                                GUI.currentUserAccount = GUI.MasterTable.insertUserAccount(user);
                                if (GUI.currentUserAccount != null)
                                {
                                    GUI.currentUserAccount.setFirstName(firstName.getText());
                                    GUI.currentUserAccount.setLastName(name2);
                                    GUI.currentUserAccount.setUserName(user);
                                    GUI.currentUserAccount.setPassword(pass1);
                                    GUI.currentUserAccount.setEmail(input3);
                                    GUI.currentUserAccount.setPhone(phone1.getText());
                                    System.out.println("You have successfully created your user account!");
                                    JOptionPane.showMessageDialog(null, "You have successfully created your user account!", "Success!",
                                            JOptionPane.INFORMATION_MESSAGE);
                                    operationSuccessful = true;
                                    CardLayout layout = (CardLayout) (MainPanel.getLayout());
                                    //send the layout of MainPanel to new display of JPanel "MainMenu"
                                    layout.show(MainPanel, "Login");
                                }
                                
                                /*else
                                {
                                    //print a pop up error
                                    System.out.println("Error creating an account!");
                                    JOptionPane.showMessageDialog(null, "Error creating an account!", "IN USE",
                                            JOptionPane.INFORMATION_MESSAGE);
                                }
                                 UserAccount retVal = GUI.MasterTable.findUserAccount(username.getText());
                                 if (retVal == null){
                                
                                 UserAccount newUser = new UserAccount();
                               
                                 newUser.setFirstName(firstName.getText());
                                 newUser.setLastName(name2);
                                 newUser.setUserName(user);
                                 //newUser.setPassword(password.getText());
                                 newUser.setPassword(pass1);
                                 newUser.setEmail(input3);
                                 newUser.setPhone(phone.getText());
                                 newUser = GUI.MasterTable.insertUserAccount(user);*/
                                //  System.out.print("\nnewUser pass inserting to MasterTable: " newUser.getPassword()+ "\n");
                            }

                            //UserAccount currentUserAccount = new UserAccount(firstName.getText(),lastName.getText(),username.getText(),password.getText(),email.getText(), phone.getText(), "");
                        }
                    }
                }
            }
        }
        //}

        if (!operationSuccessful)
        {
            System.out.println("Error with input format!");
            JOptionPane.showMessageDialog(null, "Error creating an account! INVALID FORMAT", "INVALID FORMAT", JOptionPane.INFORMATION_MESSAGE);
        }

        /*//If we reach here, user name was 100% successfully inserted into table.
         //ANY TIME THERE's DATA CHANGING (viewing information doesn't count as changing EXPORT!
         else
         {
         ImportExport dataout = new ImportExport();
         if (dataout.exportDB(GUI.MasterTable))
         {
         System.out.println("\nExported file to local source file"
         + " THROUGH CREATE ACCOUNT GUI\n");

         }
         else
         {
         System.err.println("\n\nCould not export THROUGH CREATE ACCOUNT GUI, ERROR\n\n");
         }

         }*/

    }//GEN-LAST:event_createUserAccountActionPerformed

    private void dismissViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dismissViewMouseClicked
        CardLayout layout = (CardLayout) (MainPanel.getLayout());
        layout.show(MainPanel, "Login");
    }//GEN-LAST:event_dismissViewMouseClicked

    private void firstNameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_firstNameFocusGained
    {//GEN-HEADEREND:event_firstNameFocusGained
        firstName.setText("");
    }//GEN-LAST:event_firstNameFocusGained

    private void lastNameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_lastNameFocusGained
    {//GEN-HEADEREND:event_lastNameFocusGained
        lastName.setText("");
    }//GEN-LAST:event_lastNameFocusGained

    private void usernameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_usernameFocusGained
    {//GEN-HEADEREND:event_usernameFocusGained
        username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_passwordFocusGained
    {//GEN-HEADEREND:event_passwordFocusGained
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void confirmPasswordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_confirmPasswordFocusGained
    {//GEN-HEADEREND:event_confirmPasswordFocusGained
        confirmPassword.setText("");
    }//GEN-LAST:event_confirmPasswordFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_emailFocusGained
    {//GEN-HEADEREND:event_emailFocusGained
        email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void phone1FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_phone1FocusGained
    {//GEN-HEADEREND:event_phone1FocusGained
        phone1.setText("");
    }//GEN-LAST:event_phone1FocusGained

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private static boolean validatePhoneNumber(String phoneNo)
    {
        //validate phone numbers of format "1234567890"
        if (phoneNo.matches("\\d{10}"))
            return true;

        //validating phone number with -, . or spaces
        else if (phoneNo.matches("\\d{3}[-\\.\\s]\\d{3}[-\\.\\s]\\d{4}"))
            return true;

        //validating phone number with extension length from 3 to 5
        else if (phoneNo.matches("\\d{3}-\\d{3}-\\d{4}\\s(x|(ext))\\d{3,5}"))
            return true;

        //validating phone number where area code is in braces ()
        else if (phoneNo.matches("\\(\\d{3}\\)-\\d{3}-\\d{4}"))
            return true;

        //return false if nothing matches the input
        else
            return false;
    }

    private static boolean isValidEmailAddress(String email)
    {
        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
        java.util.regex.Matcher m = p.matcher(email);
        return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.PopupMenu ERRORPOP;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JButton createUserAccount;
    private javax.swing.JButton dismissView;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastName;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone1;
    private javax.swing.JTextField phone2;
    private javax.swing.JTextField phone3;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
