/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Ryan
 */
public class CreateBankAccount extends javax.swing.JPanel
{

    private JPanel MainPanel;
    private GUI mainGUI;
    String[] accTypes =
    {
        "Checking", "Savings"
    };

    public CreateBankAccount(JPanel MainPanel, GUI mainGUI)
    {
        this.mainGUI = mainGUI;
        this.MainPanel = MainPanel;
        initComponents();
    }
    
    public void updateUserLabel()
    {
        BAUserLabel.setText(GUI.currentUserAccount.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountNameField = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox();
        CreateButton = new javax.swing.JButton();
        BAUserLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        AccountNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AccountNameFieldFocusGained(evt);
            }
        });
        AccountNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountNameFieldActionPerformed(evt);
            }
        });

        TypeCombo.setModel(new DefaultComboBoxModel(accTypes));

        CreateButton.setText("Create Bank Account");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        BAUserLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BAUserLabel.setText("jLabel2");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateButton)
                .addGap(313, 313, 313))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BAUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AccountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BAUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeCombo))
                .addGap(89, 89, 89)
                .addComponent(AccountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(CreateButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AccountNameFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_AccountNameFieldFocusGained
    {//GEN-HEADEREND:event_AccountNameFieldFocusGained
        AccountNameField.setText("");
    }//GEN-LAST:event_AccountNameFieldFocusGained

    private void AccountNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AccountNameFieldActionPerformed
    {//GEN-HEADEREND:event_AccountNameFieldActionPerformed
        if (AccountNameField.getText().length() > 0 && GUI.currentUserAccount.findBankAccount(AccountNameField.getText()) == null)
        {
            GUI.currentUserAccount.insertBankAccount(0, AccountNameField.getText(), TypeCombo.getSelectedItem().toString());
            CardLayout layout = (CardLayout) (MainPanel.getLayout());
            layout.show(MainPanel, "AccList");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid input");
            AccountNameField.setText("");
        }
    }//GEN-LAST:event_AccountNameFieldActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateButtonActionPerformed
    {//GEN-HEADEREND:event_CreateButtonActionPerformed
        if (AccountNameField.getText().length() > 0 && GUI.currentUserAccount.findBankAccount(AccountNameField.getText()) == null)

        {
            GUI.currentUserAccount.insertBankAccount(0, AccountNameField.getText(), TypeCombo.getSelectedItem().toString());
            CardLayout layout = (CardLayout) (MainPanel.getLayout());
            mainGUI.getAccList().update();
            layout.show(MainPanel, "AccList");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid input");
            AccountNameField.setText("");
        }
        
    }//GEN-LAST:event_CreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNameField;
    private javax.swing.JLabel BAUserLabel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JComboBox TypeCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
