/**
 * **************************************************************************
 *
 * Aryaman Sharda CSE 110, Fall 2014 Last Updated: December 6, 2014
 *
 * Team 42
 *
 * File Name: ForgotPasswordPanel.java Description: This file contains the
 * implementation of a form that aids the user in resetting their password
 * if forgotten.
 * **************************************************************************
 */

package PresentationLayer;

import javax.swing.JPanel;

/**
 *
 * @author Aryaman Sharda
 */
public class ForgotPasswordPanel extends javax.swing.JPanel
{
    //Stores a reference to the main panel from the GUI
    private JPanel MainPanel;
    
    //Stores a reference to the mainGUI object
    private GUI mainGUI;

    /**
     * Creates new form PasswordFieldPanel
     */
    public ForgotPasswordPanel()
    {
        initComponents();
    }

    /* 
     This constructor takes in MainPanel from GUI.java which gives us access to
     the main panel where all of our GUI elements will eventually be located. */
    
    public ForgotPasswordPanel(JPanel MainPanel, GUI mainGUI)
    {
        this.MainPanel = MainPanel;
        this.mainGUI = mainGUI;
        initComponents();
    }

    /**
     * This function return this current panel
     *
     * method: GetPanel    
     * @return Returns this panel so it can be shown on other screens
     * Returns a JPanel object
     */
    public javax.swing.JPanel GetPanel()
    {
        return this;
    }

    /**
     * This function return the password from the text field
     *
     * method: GetPassword    
     * @return Returns the password from the text field
     * Returns the password from the text field on the screen.
     */
    public String GetPassword()
    {
        char[] passwordArray = jPasswordField.getPassword();
        String password = new String(passwordArray);
        return password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPasswordField = new javax.swing.JPasswordField();
        EnterPassword = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPasswordField.setText("password");
        jPasswordField.setMinimumSize(new java.awt.Dimension(95, 25));
        jPasswordField.setPreferredSize(new java.awt.Dimension(95, 25));
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jPasswordField, gridBagConstraints);

        EnterPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EnterPassword.setText("Please enter your new password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(EnterPassword, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function will reset the password field when the user
     * clicks on the text box
     *      
     * method: jPasswordFieldFocusGained
     * @param evt A focus event that triggers the reset of the text field          
     */
    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jPasswordFieldFocusGained
    {//GEN-HEADEREND:event_jPasswordFieldFocusGained
        //Clears the content in the text field
        jPasswordField.setText("");
    }//GEN-LAST:event_jPasswordFieldFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterPassword;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
